# global default
container:
  image: node:10-alpine

task:
  name: Lint
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  lint_script: yarn lint

task:
  name: Test
  env:
    CC_TEST_REPORTER_ID: ENCRYPTED[c24ecdbc2beed1837ff7c8f0b571e5bb29eaa542012c6839844fb6f17ebbd46532bb1ea4b20c9580ecc2ef995b6275d1]
    GIT_COMMIT_SHA: $CIRRUS_CHANGE_IN_REPO
    GIT_BRANCH: $CIRRUS_BRANCH
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  codeclimate_before_test_script:
    - wget -c https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -O cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
  test_script: yarn test
  codeclimate_after_test_script: ./cc-test-reporter after-build --exit-code $?

task:
  name: Linux build
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn build

task:
  name: Windows build
  windows_container:
    image: cirrusci/windowsservercore:2016
  depends_on:
    - Lint
    - Test
  yarn_install_script:
    - powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://yarnpkg.com/latest.msi -OutFile $env:TEMP\yarn.msi"
    - msiexec /i "%TEMP%\yarn.msi" /quiet
  node_modules_cache:
    folder: node_modules
    fingerprint_script: type yarn.lock
    populate_script: yarn install
  build_script: yarn build

task:
  name: macOS build
  osx_instance:
    image: mojave-base
  env:
    HOMEBREW_NO_AUTO_UPDATE: 1
  yarn_install_script:
    - brew install yarn
    - brew link --force yarn
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn build

task:
  name: Publish
  depends_on:
    - Linux build
    - Windows build
    - macOS build
  only_if: $BRANCH == "master"
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  publish_script: echo "Publish!"
