language: node_js

node_js:
  - lts/*

os:
  - windows
  - linux
  - osx

branches:
  only: develop

cache: yarn

jobs:
  include:
    - stage: Cache dependencies
      script: true
    - stage: Build
      script: |
        - yarn build
        - if [ -n "$TRAVIS_TAG" ]; then echo upload; fi
    - stage: Publish
      if: tag is present
      install: skip
      script: echo publish

script:
  - yarn build
