language: node_js
node_js: lts/*
os: osx
osx_image: xcode9.4
addons:
  homebrew:
    packages:
    - rpm
branches:
  only: master
cache:
  - yarn
  - directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
script:
  - yarn lint
  - yarn build -lwm
