language: node_js

node_js:
  - lts/*

branches:
  only: master

cache: yarn

jobs:
  include:
    - stage: Cache dependencies
      os:
        - windows
        - linux
        - osx
      script: true
    - stage: Build
      os:
        - windows
        - linux
        - osx
      script: |
        - yarn build
        - if [ -n "$TRAVIS_TAG" ]; then echo upload; fi
    - stage: Publish
      if: tag is present
      install: skip
      script: echo publish

script:
  - yarn build
