language: node_js

node_js:
  - lts/*

os:
  - linux
  - windows
  - osx

branches:
  only: develop

cache: yarn

script:
  - yarn lint
  - yarn build
  - if [ -n "$TRAVIS_TAG" ]; then echo upload; fi

jobs:
  include:
    - stage: Publish
      if: tag is present
      install: skip
      script: echo publish
