export const assistantLangs = {
  'en-US': 'English (US)',
  'en-GB': 'English (GB)',
  'en-AU': 'English (AU)',
  'en-SG': 'English (SG)',
  'en-CA': 'English (CA)',
  'de-DE': 'German',
  'fr-FR': 'French (FR)',
  'fr-CA': 'French (CA)',
  'ja-JP': 'Japanese',
  'ko-KR': 'Korean',
  'es-ES': 'Spanish (European)',
  'es-419': 'Spanish (Latin America)',
  // 'es-MX': 'Spanish (Mexico)',
  // 'es-US': 'Spanish (US)',
  'pt-BR': 'Portuguese',
  'it-IT': 'Italian',
  'ru-RU': 'Russian',
  'hi-IN': 'Hindi',
  'th-TH': 'Thai',
  'id-ID': 'Indonesian',
  'da-DK': 'Danish',
  'no-NO': 'Norwegian',
  'nl-NL': 'Dutch',
  'sv-SE': 'Swedish',
};
